name: Tag latest
on:
  push:
    branches: [master]

env:
  TAG_NAME: latest

jobs:
  tag-repo:
    if: "!contains(github.event.commits[0].message, 'Bump Version:')"
    runs-on: ubuntu-latest
    outputs:
      TAG_NAME: ${{ env.TAG_NAME }}
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.NANOME_BOT_PAT }}
    - name: git setup
      run: |
        git config --global user.name 'nanome-bot'
        git config --global user.email '45469149+nanome-bot@users.noreply.github.com'
  push-to-registry:
    needs: "tag-repo"
    uses: ./.github/workflows/push-to-registry.yml
    with:
      tag: ${{needs.tag-repo.outputs.TAG_NAME}}
    secrets: inherit
