name: Unittests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip coverage
          pip install -r requirements.txt
          conda env update -f adfr-suite.yml
          chmod +x nanome_docking/smina/smina_binary
          chmod +x nanome_docking/autodock4/vina_1.2.2_linux_x86_64

      - name: Run tests.py
        run: coverage run --source=nanome_docking --omit nanome_docking/rhodium/calculations.py,nanome_docking/menus/DockingMenuRhodium.py -m unittest discover tests
      - name: print coverage percentage
        run: coverage report | grep TOTAL
