name: Unittests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  smina-unittests:
    env:
      DOCKER_BUILDKIT: 1
    name: Smina Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker image
      run: cd docker && ./build.sh --algorithm smina

    - name: Run tests
      run: docker run --rm docking-smina python -m unittest discover tests.smina
